branches:
    only:
        - master
version: 1.0.{build}
environment:
  GITHUB_USERNAME:
    secure: 0Q9MvUId56SizmZwCf0cgg==
  GITHUB_TOKEN:
    secure: R3xA9iMXfUUtFd3wuL38pcDa0/BjjpBvNcGShr5LRibZtBoOVSH47Jat75rwaGur
  NUGET_SOURCE: https://www.nuget.org/api/v2/package
  NUGET_TOKEN:
    secure: 0g2AqQxgiAIFhqoJbbmEPrJa15Z8U5xYT6vQe43Gocuxbjw74hBAIKbU+Cj65UNd
build_script:
- ps: >-
    ./bootstrap.ps1

    ./build.cmd
artifacts:
- path: artifacts/*
- path: '**/bin/*'